export interface Art {
  id: string
  name: string
  image: string
  hi_res_texture: string
  genuine: string
  category: string
  buy_price: number
  sell_price: number
  color1: string
  color2: string
  size: string
  real_artwork_title: string
  artist: string
  description: string
  source: string
  source_notes: string
  hha_base_points: number
  hha_concept1: string
  hha_concept2: string
  hha_series: string
  hha_set: string
  interact: string
  tag: string
  speaker_type: string
  lighting_type: string
  catalog: string
  unlocked: string
  donated: boolean
}
